Repository Zizzamia/perfume.js, pull requests merged in 2018-05, with the labels that each got.

#30 build: Minify umd bundle
  .gitignore
  README.md
  dist/es/emulated-performance.js
  dist/es/emulated-performance.js.map
  dist/es/performance-impl.js
  dist/es/performance-impl.js.map
  dist/es/performance.js
  dist/es/performance.js.map
  dist/es/perfume.js
  dist/es/perfume.js.map
  dist/lib/emulated-performance.js
  dist/lib/emulated-performance.js.map
  dist/lib/performance-impl.js
  dist/lib/performance-impl.js.map
  dist/lib/performance.js
  dist/lib/performance.js.map
  dist/lib/perfume.js
  dist/lib/perfume.js.map
  dist/perfume.es5.js
  dist/perfume.es5.js.map
  dist/perfume.iife.js
  dist/perfume.iife.js.map
  dist/perfume.umd.js
  dist/perfume.umd.js.map
  dist/types/emulated-performance.d.ts
  dist/types/performance-impl.d.ts
  dist/types/performance.d.ts
  dist/types/perfume.d.ts
  rollup.config.ts
Labels: build

#31 style: update tslint
  __tests__/emnulated-performance.spec.ts
  __tests__/performance.spec.ts
  __tests__/perfume.spec.ts
  package-lock.json
  package.json
  src/emulated-performance.ts
  src/performance-impl.ts
  src/performance.ts
  src/perfume.ts
  tslint.json
Labels: fix

#29 refactor: tests
  __tests__/_mock.ts
  __tests__/emnulated-performance.spec.ts
  __tests__/performance.spec.ts
  __tests__/perfume.spec.ts
  package.json
  src/emulated-performance.ts
Labels: refactor
